import { sample } from "lodash";

const eventsTable = [
  {
    type: "Rise of a leader or an era",
    subTable: [
      "Political",
      "Religious",
      "Military",
      "Crime/underworld",
      "Art/culture",
      "Philosophy/learning,/agic",
    ],
  },
  {
    type: "Fall of a leader or an era",
    subTable: [
      "Political",
      "Religious",
      "Military",
      "Crime/underworld",
      "Art/culture",
      "Philosophy/learning,/agic",
    ],
  },
  {
    type: "Cataclysmic disaster",
    subTable: [
      "Earthquake",
      "Faminef drought",
      "Fire",
      "Flood",
      "Plaguefdisease",
      "Rain of fire (meteoric impact)",
      "Storm (hurricane, tornado, tsunami)",
      "Volcanic eruption",
      "Magic gone awry or a planar warp",
      "Divine judgment",
    ],
  },
  {
    type: "Assault or invasion",
    subTable: [
      "A criminal enterprise",
      "Monsters or a unique monster",
      "A planar threat",
      "A past adversary reawakened, reborn, or resurgent",
      "A splinter faction",
      "A savage tribe",
      "A secret society",
      "A traitorous ally",
    ],
  },
  { type: "Rebellion, revolution, overthrow" },
  {
    type: "Extinction or depletion",
    subTable: [
      "A kind of animal (insect , bird, fish, livestock)",
      "Habitable land",
      "Magic or magic-users (all magic, or specific kinds or schools of magic)",
      "A mineral resource (gems, metals, ores)",
      "A type of monster (unicorn, manticore, dragon)",
      "A people (family line, clan, culture, race)",
      "A kind of plant (crop, tree, herb, forest)",
      "A waterway (river, lake, ocean)",
    ],
  },
  {
    type: "New organization",
    subTable: [
      "Crime syndicate/bandit confederacy",
      "Guild (masons, apothecaries, goldsmiths)",
      "Magical circle/society",
      "Military/knightly order",
      "New family dynasty/tribe/clan",
      "Philosophy/discipline dedicated to a principle or ideal",
      "Realm (village, town, duchy, kingdom)",
      "Religion/sect/denomination",
      "School/university",
      "Secret society/cult/cabal",
    ],
  },
  {
    type: "Discovery, expansion, invention",
    subTable: [
      "Ancient ruin/lost city of a legendary race",
      "Animal/monster/magical mutation",
      "Invention/technology/magic (helpful, destructive)",
      "New (or forgotten) god or planar entity",
      "New (or rediscovered) artifact or religious relic",
      "New land (island, continent, lost world, demiplane)",
      "Otherworldly object (planar portal, alien spacecraft)",
      "People (race, tribe, lost civilization, colony)",
      "Plant (miracle herb, fungal parasite, sentient plant)",
      "Resource or wealth (gold, gems, mithral)",
    ],
  },
  { type: "Prediction, omen, prophecy" },
  {
    type: "Myth and legend",
    subTable: [
      "Rise of a leader or an era",
      "Fall of a leader or an era",
      "Cataclysmic disaster",
      "Assault or invasion",
      "Rebellion, revolution, overthrow",
      "Extinction or depletion",
      "New organization",
      "Discovery, expansion, invention",
    ],
  },
  { type: "Anniversary of a monarch's reign " },
  { type: "Anniversary of an important event " },
  { type: "Arena event" },
  { type: "Arrival of a caravan or ship" },
  { type: "Arrival of a circus" },
  { type: "Arrival of an important NPC" },
  { type: "Arrival of marching modrons" },
  { type: "Artistic performance" },
  { type: "Athletic event" },
  { type: "Birth of a child" },
  { type: "Birthday of an important NPC" },
  { type: "Civic festival" },
  { type: "Comet appearance" },
  { type: "Commemoration of a past tragedy" },
  { type: "Consecration of a new temple" },
  { type: "Coronation" },
  { type: "Council meeting" },
  { type: "Equinox or solstice  " },
  { type: "Execution" },
  { type: "FertiIity festivaI" },
  { type: "Full moon" },
  { type: "Funeral" },
  { type: "Graduation of cadets or wizards" },
  { type: "Harvest festival" },
  { type: "Holy day" },
  { type: "Investiture of a knight or other noble" },
  { type: "Lunar eclipse" },
  { type: "Midsummer festival" },
  { type: "Midwinter festival" },
  { type: "Migration of monsters" },
  { type: "Monarch's ball" },
  { type: "New moon" },
  { type: "New year" },
  { type: "Pardoning of a prisoner" },
  { type: "Planar conjunction" },
  { type: "Planetary alignment" },
  { type: "Priestly investiture" },
  { type: "Procession of ghosts" },
  { type: "Remembrance for soldiers lost in war " },
  { type: "Royal address or proclamation" },
  { type: "Royal audience day" },
  { type: "Signing of a treaty" },
  { type: "Solar eclipse" },
  { type: "Tournament" },
  { type: "Trial" },
  { type: "Violent uprising" },
  { type: "Wedding or wedding anniversary" },
];

export interface GeneratedEvent {
  type?: string;
  subType?: string;
}

export const generateEvent = (): GeneratedEvent => {
  const eventType = sample(eventsTable);
  const subType = sample(eventType?.subTable);
  return {
    type: eventType?.type,
    subType,
  };
};
